### ISSUE TITLE
Potential Place to use CAP's User entity

### ISSUE THREAD

**Issue by zkud** [AlexBerlimon/CAPsidian#1]
https://github.com/AlexBerlimon/CAPsidian/blob/fc16736fab335314b1e7ba07d5fca02fb70ee936/db/models/clients.cds#L8

**Comment by AlexBerlimon** [comment]
Hi! In the 83260d6 commit i fixed this issue, please check and give your feedback about that

**Comment by zkud** [comment]
lgtm
