### ISSUE TITLE
Redundant Service

### ISSUE THREAD

**Issue by zkud** [AlexBerlimon/CAPsidian#2]
https://github.com/AlexBerlimon/CAPsidian/blob/fc16736fab335314b1e7ba07d5fca02fb70ee936/srv/services/clients-service.cds#L3-L9

1. SAP BTP IdP should be used instead.
2. instance-based auth should be used instead.

**Comment by AlexBerlimon** [comment]
OK, I get it and i have just fixed in the 83260d6 commit. Added instanse-based authority, added roles. After deploy i am going to link BTP IdP to our project
